CREATE TABLE IF NOT EXISTS TEST_TABLE(COL1 INTEGER NOT NULL, COL2 CHAR(25), COL3 VARCHAR(25) NOT NULL, COL4 DATE, PRIMARY KEY (COL1));

CREATE ALIAS get_test FOR "org.breitling.dragon.framework.test.Functions.getTest";

